#TRIGGER PARA ACTUALIZAR LAS CALIFICAIONES DE PUBLICACIONES (UPVOTE - DOWNVOTE)

DELIMITER &&
CREATE TRIGGER tg_ActualizarCalificaciones
BEFORE UPDATE
ON publicaciones
FOR EACH ROW
BEGIN 
	SET NEW.calificacion = NEW.upvote - NEW.downvote;

END &&
DELIMITER ;